sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly"
services:
  - redis-server
install:
  - "if [[ $REDIS_VERSION == '3.0' ]]; then REDIS_VERSION=3.0 make redis-install; fi"
  - "if [[ $REDIS_VERSION == '3.2' ]]; then REDIS_VERSION=3.2 make redis-install; fi"
  - "if [[ $REDIS_VERSION == '4.0' ]]; then REDIS_VERSION=4.0 make redis-install; fi"
  - pip install -r dev-requirements.txt
  - pip install -e .
  - "if [[ $HIREDIS == '1' ]]; then pip install hiredis; fi"
env:
  # Redis 3.0
  - HIREDIS=0 REDIS_VERSION=3.0
  # Redis 3.0 and HIREDIS
  - HIREDIS=1 REDIS_VERSION=3.0
  # Redis 3.2
  - HIREDIS=0 REDIS_VERSION=3.2
  # Redis 3.2 and HIREDIS
  - HIREDIS=1 REDIS_VERSION=3.2
  # Redis 4.0
  - HIREDIS=0 REDIS_VERSION=4.0
  # Redis 4.0 and HIREDIS
  - HIREDIS=1 REDIS_VERSION=4.0
script: 
  - make start
  - coverage erase
  - coverage run --source rediscluster -p -m py.test
  - make stop
after_success: 
  - coverage combine
  - coveralls
matrix:
  allow_failures:
    - python: "nightly"
